name: Azure Functions CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Ajuste para a versão correta do .NET (no caso 8.0.x)

    - name: Navigate to project directory  # Adiciona este passo para entrar no diretório correto
      run: cd C:/Projetos/TechChallengeFiapFunction/cpf-auth-function

    - name: Install dependencies
      run: dotnet restore cpf-auth-function.csproj  # Restaura as dependências com o caminho correto

    - name: Build the project
      run: dotnet build cpf-auth-function.csproj --configuration Release --output ./output  # Compila o projeto no caminho correto

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: MyCpfAuthFunction   # Nome da sua Azure Function
        package: './output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: Notify GitHub
      run: echo "Deploy feito com sucesso!"
