name: Azure Functions CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Ambiente Linux

    steps:
    - name: Checkout repository  # Faz o checkout do código
      uses: actions/checkout@v2

    - name: Setup .NET Core  # Configura o .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore ./cpf-auth-function/cpf-auth-function.csproj  # Caminho relativo ao arquivo .csproj

    - name: Build the project
      run: dotnet build ./cpf-auth-function/cpf-auth-function.csproj --configuration Release --output ./output  # Caminho relativo ao arquivo .csproj

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: MyCpfAuthFunction   # Nome da sua Azure Function
        package: './output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: Notify GitHub
      run: echo "Deploy feito com sucesso!"
